### ISSUE TITLE
`SDL2_image` not found on Windows

### ISSUE THREAD

**Issue by fxrysh** [littledivy/deno_sdl2#51]
I boot up a Windows VM, install SDL2 and put it in my current working directory. And run the example.
```cmd
C\> SET "DENO_SDL2_PATH=%CD%"
C\> deno run --allow-env --allow-ffi --unstable https://deno.land/x/sdl2/examples/hello.ts
```
After running *that*, I get the following error:
```js
error: Uncaught Error: Could not open library: The specified module could not be found.

const sdl2Image = Deno.dlopen(getLibraryPath("SDL2_image"), {
                       ^
    at Object.opSync (deno:core/01_core.js:174:12)
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:231:24)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:329:12)
    at https://deno.land/x/sdl2@0.5.1/mod.ts:245:24
```
The thing is, `SDL2_image.dll` exist in the same directory as `SDL2.dll` and `SDL2_ttf.dll`.
```cmd
C\> DIR | FINDSTR /c:"SDL2"
13/01/2022  03:14 AM         1,763,967 SDL2.dll
31/07/2021  08:20 PM           137,492 SDL2_image.dll
13/01/2022  03:18 AM            69,473 SDL2_ttf.dll
```
What could be the problem? Is it because of my VM?

**Comment by fxrysh** [comment]
Fixed it. Sorry for bothering
