### ISSUE TITLE
Uncaught TypeError: Invalid FFI pointer type, expected null, integer or BigInt

### ISSUE THREAD

**Issue by tylerchilds** [littledivy/deno_sdl2#55]
Trying to run the hello.ts example, but getting an error, pasted below. This happens on multiple machines on the latest deno. The most recent version of deno I have laying around where the code works is 1.23.2.

```
tychi@pop-os:~/SourceCode/deno_sdl2$ deno run --allow-ffi --unstable examples/hello.ts --no-check
⚠️  ️Deno requests env access to "DENO_SDL2_PATH". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
SDL2 initialized on Linux
error: Uncaught TypeError: Invalid FFI pointer type, expected null, integer or BigInt
    const window = sdl2.symbols.SDL_CreateWindow(
                                ^
    at Object.eval [as SDL_CreateWindow] (eval at DynamicLibrary (deno:ext/ffi/00_ffi.js:366:34), <anonymous>:4:13)
    at WindowBuilder.build (file:///home/tychi/SourceCode/deno_sdl2/mod.ts:956:33)
    at file:///home/tychi/SourceCode/deno_sdl2/examples/hello.ts:4:60
tychi@pop-os:~/SourceCode/deno_sdl2$ 
```

**Comment by AngelGamer29JA** [comment]
I've been trying to fix this error and it happens on line 62, in parameters where pointer should be buffer

```json
  "SDL_CreateWindow": {
    "parameters": [
      "pointer", // <--- this line should be replaced by "buffer"
      "i32",
```
